### ISSUE TITLE
Build project failed 

### ISSUE THREAD

**Issue by iotproductions** [nopnop2002/esp-idf-remote-camera#16]
Hi,

I got some errors as below picture when try to build your project:
![image](https://user-images.githubusercontent.com/6419276/206642132-bcc12d03-c0b9-42ee-b572-25b8d3d4bc2b.png)
Seem the project on your Github missing a Makefile?
Please let me know what is wrong ?
Thanks !

**Comment by nopnop2002** [comment]
>Seem the project on your Github missing a Makefile?

The "make" build system was deprecated in v4.0 in favor of idf.py (cmake). 
So there is no Makefile.



I used this ESP-IDF.
```
$ idf.py --version
ESP-IDF v4.4.3-171-gbe9d294718
```

If you use 4.4.1 or 4.4.2 you may need to delete idf_component.yml.

```
rm main/idf_component.yml
idf.py set-target esp32
idf.py menuconfig
idf.py build
```

**Comment by iotproductions** [comment]
Hi @nopnop2002 !

Thank for your information !
It's work now !
```
rm main/idf_component.yml
idf.py set-target esp32
idf.py menuconfig
idf.py build
```
![2022-12-09_145153](https://user-images.githubusercontent.com/6419276/206941690-5aaec5aa-02a1-406a-9885-ca8566f064a8.jpg)
